"use strict";
import { DateUtils } from "./lib/date";
import { StringUtils } from "./lib/string";
import { ArrayUtils } from "./lib/arrays";
import { FetchUtils } from "./lib/fetchs";
import { MathUtils } from "./lib/math";
import { NumberUtils } from "./lib/numbers";
import { ObjectUtils } from "./lib/objects";
import { Validators } from "./lib/validators";
import { GeoUtils } from "./lib/geo";
import { BankCardUtils } from "./lib/cards";
import { EncryptionUtils } from "./lib/encrypt";
import { BrowserUtils } from "./lib/browser";
import { SecurityUtils } from "./lib/security";

export const DATE = DateUtils;
export const STRING = StringUtils;
export const ARRAY = ArrayUtils;
export const FETCH = FetchUtils;
export const MATH = MathUtils;
export const NUMBER = NumberUtils;
export const OBJECTS = ObjectUtils;
export const VALIDATORS = Validators;
export const GEO = GeoUtils;
export const BANKCARDS = BankCardUtils;
export const ENCRYPT = EncryptionUtils;
export const BROWSER = BrowserUtils;
export const SECURITY = SecurityUtils;
